<?php

namespace Troiswa\PublicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends EntityRepository

{

    public function getNbFilmByCategorie()

    {

            $req=$this->getEntityManager()->createQuery(
            "Select Count(f.id) AS nbFilm, c.titre 
            FROM TroiswaPublicBundle:Film f
            LEFT JOIN f.categorie c
            GROUP BY c.id"

        );
        
         return $req->getResult();

    }

}
/*
l'equivalent de la requette en sql
SELECT categorie.titre, Count(*)
FROM  film 
LEFT JOIN categorie on film.categorie_id=categorie.id
GROUP BY categorie.id
*/